# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only

# ---
# tasks file for roles/org

---
# tasks file for org

- name: create org
  vcd_org:
    org_name: acme_sample
    full_name: acme_sample
    is_enabled: true
    state: present
  register: output

- name: create org output
  debug:
    msg: '{{ output }}'

- name: update org
  vcd_org:
    org_name: acme_sample
    is_enabled: false
    state: update
  register: output

- name: update org output
  debug:
    msg: '{{ output }}'

- name: read org
  vcd_org:
    org_name: acme_sample
    is_enabled: true
    operation: read
  register: output

- name: read org output
  debug:
    msg: '{{ output }}'

- name: add rights to org
  vcd_org:
    org_name: acme_sample
    org_rights:
      - "Catalog: Import Media from vSphere"
    operation: add_rights
  register: output

- name: add rights output
  debug:
    msg: '{{ output }}'

- name: list rights of org
  vcd_org:
    org_name: acme_sample
    operation: list_rights
  register: output

- name: add rights output
  debug:
    msg: ' {{ output }}'

- name: list roles
  vcd_org:
    org_name: acme_sample
    operation: list_roles
  register: output

- name: list roles output
  debug:
    msg: '{{ output }}'

- name: list vdcs
  vcd_org:
    org_name: Acme
    operation: list_vdcs
  register: output

- name: list vdcs output
  debug:
    msg: '{{ output }}'

- name: delete org
  vcd_org:
    org_name: acme_sample
    state: absent
  register: output

- name: delete org output
  debug:
    msg: '{{ output }}'
