---
- name: vCloudDirectorAnsible
  hosts: localhost
  environment:
       env_user: "{{ vcloud_username }}"
       env_password: "{{ vcloud_password }}"
       env_host: "{{ vcloud_host }}"  
       env_verify_ssl_certs: false
  tasks:
  - name: create org
    vcd_org:
         org_name: "test_org"
         full_name: "test_org"
         is_enabled : "false"
         state: "present"
#      user: "{{ vcloud_username }}"
#      password: "{{ vcloud_password }}"
#      host: "{{ vcloud_host }}"
