---
- name: Create VM from Vcenter Template
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Clone Template to New Virtual Machine
      community.vmware.vmware_guest:
        validate_certs: false
        name: "{{ vm_name }}"
        template: plantilla_helper_airgap
        datacenter: DCUIO
        resource_pool: # Input Resource Pool
        folder: "/DCUIO/vm/AWX"
        state: poweredon
        wait_for_ip_address: true
        wait_for_customization: true
        networks:
          - name: "{{ vm_net_namelan }}"
            ip: "{{ vm_iplan }}"
            netmask: "{{ vm_net_mask_lan }}"
            gateway: "{{ vm_net_gw }}"
          - name: "{{ vm_net_namesan }}"
            ip: "{{ vm_ipsan }}"
            netmask: "{{ vm_net_mask_san }}"
          - name: "{{ vm_net_namemgmt }}"
            ip: "{{ vm_ipmgmt }}"
            netmask: "{{ vm_net_mask_mgmt }}"
            
        customization:
          dns_servers:
          - "{{ vm_net_dns }}"
          
    - name: Pause for 30 seconds to wait for reboot
      ansible.builtin.pause:
        seconds: "120"
    


- name: Set VM IP and Hostname
  hosts: "{{ vm_ipmgmt }}" # This is the IP that is set for the template, if you use a different IP update here.
  become: true
  gather_facts: false
  tasks:
        
    - name: Update IP escucha
      ansible.builtin.lineinfile:
        path: /etc/bind/named.conf.options
        regex: "10.10.5.73" # Set to same IP as line 19
        line: "        listen-on port 53 { {{ vm_iplan }}; };"
        
    - name: Update red origen
      ansible.builtin.lineinfile:
        path: /etc/bind/named.conf.options
        regex: "10.10.5.64/28" # Set to same IP as line 19
        line: "        allow-query { {{ vm_nwlan }}/{{ new_prefix }}; };"

    - name: Update recursion
      ansible.builtin.lineinfile:
        path: /etc/bind/named.conf.options
        regex: "10.10.5.65/28" # Set to same IP as line 19
        line: "        allow-recursion { {{ vm_nwlan }}/{{ new_prefix }}; };"

    - name: Update namedlocal
      ansible.builtin.lineinfile:
        path: /etc/bind/named.conf.local
        regex: "vlan110" # Set to same IP as line 19
        line: "zone \"{{ fqdn_nas }}\" IN {"

    - name: Update fwrds
      ansible.builtin.lineinfile:
        path: /etc/bind/named.conf.local
        regex: "172.16.138.127" # Set to same IP as line 19
        line: "        forwarders { {{ new_fwrds }}; };"
        
    - name: Restart service httpd, in all cases
      ansible.builtin.service:
        name: bind9
        state: restarted


        
    
        
