---
- name: vCloudDirectorAnsible
  hosts: localhost
  environment:
       env_user: "{{ vcloud_username }}"
       env_password: "{{ vcloud_password }}"
       env_host: "{{ vcloud_host }}"  
       env_verify_ssl_certs: false
       env_api_version: 32.0

  tasks:
  - name: read org
    vcd_org:
         org_name: Cliente-test
         is_enabled: true
         operation: read
         register: output

  - name: read org output
    debug:
      msg: '{{ output }}'
#  - name: create org
#    vcd_org:
#         org_name: test_org
#         full_name: test_org
#         is_enabled: true
#         state: present
#         org: "System"
#    register: output
 #        user: "{{ vcloud_username }}"
 #        password: "{{ vcloud_password }}"
 #        host: "{{ vcloud_host }}"
 #        org: "System"
