---
- name: Changing network adapter
  hosts: localhost
  tasks:
    - name:  Changing network adapter
      community.vmware.vmware_guest:
        validate_certs: false  
        name: "{{ vm_name }}"  
        folder: "/DCUIO/vm/AWX"
        networks:
          - network_name: "dvportgroup-3076"
            connected: false
