---
- name: Changing network adapter
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name:  Changing network adapter
      community.vmware.vmware_guest_network:
        name: "{{ vm_name }}"
        networks:
        - network_name: "{{ vm_net_namemgmt }}"
          connected: False
