# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- name: vCloudDirectorAnsible
  hosts: localhost
  environment:
    env_user: terraformadmin
    env_password: XXXXXXXXXXXXX
    env_host: XXXXXXXXXXXXX
    env_org: Terraform
    env_api_version: 30.0
    env_verify_ssl_certs: false
  roles:
      - org
      - user
      - vdc
      - catalogs
      - catalog_items
      - disk
      - vapp
      - vcd_vapp_network
      - vappvm
      - external_networks
      - vcd_edge_gateway
      - org_vdc_networks
      - vcd_vapp_vm_snapshot
      - vcd_vapp_vm_disk
      - vcd_vapp_vm_nic
      - vcd_gateway_services
