---
- name: update SO
  hosts: "{{ vm_ipmgmt }}" # This is the IP that is set for the template, if you use a different IP update here.
  become: true
  gather_facts: false
  tasks:
  
  - name: Upgrade all packages
  ansible.builtin.yum:
    name: '*'
    state: latest
