---
- name: update SO
  hosts: "{{ vm_ipmgmt }}" # This is the IP that is set for the template, if you use a different IP update here.
  become: true
  gather_facts: false
  tasks:
  
  - name: Update all Debian/Ubuntu packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
